repos:
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.81.0
    hooks:
    -   id: terraform_fmt
    -   id: terrascan
        args:
         - --args=--non-recursive # avoids scan errors on subdirectories without Terraform config files
         - --args=--policy-type=azure
    - id: terraform_docs
      args:
       - --hook-config=--path-to-file=README.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
       - --hook-config=--add-to-existing-file=true     # Boolean. true or false
       - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
    - id: terraform_checkov
      args:
      - --args=--quiet
      - --args=--skip-check CKV2_AWS_8

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
